
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jayana Citra
 */
public class Setor extends javax.swing.JFrame {

    /**
     * Creates new form Setor
     */
    public Setor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JumlahUangSetor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Kirim = new javax.swing.JButton();
        BatalSetor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ATM - BNI SYARIAH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 250, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);
        jPanel1.add(JumlahUangSetor);
        JumlahUangSetor.setBounds(40, 50, 240, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Masukkan Jumlah Uang Yang Akan Dikirim");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 20, 260, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Kirim");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 90, 50, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Batal");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(240, 140, 50, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 70, 320, 180);

        Kirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KirimActionPerformed(evt);
            }
        });
        getContentPane().add(Kirim);
        Kirim.setBounds(390, 150, 60, 40);

        BatalSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalSetorActionPerformed(evt);
            }
        });
        getContentPane().add(BatalSetor);
        BatalSetor.setBounds(390, 200, 60, 40);

        setBounds(0, 0, 480, 325);
    }// </editor-fold>//GEN-END:initComponents

    private void KirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KirimActionPerformed
        // TODO add your handling code here:
        String setoran = JumlahUangSetor.getText();
            int jmlsetor = Integer.parseInt(setoran);
            int saldo = 1000000;
            int saldoakhir = saldo+jmlsetor;
            
        if (jmlsetor%100!=0) {
            JOptionPane.showMessageDialog(null, "Mesin ATM BNI tidak menerima uang koin \nSilahkan ulangi kembali!", "Transaksi Gagal", 0);
        } else if (jmlsetor<=50000) {
            JOptionPane.showMessageDialog(null, "Besaran minimal setor tunai adalah Rp 50.000,00", "ERROR", 0);
        }else if (jmlsetor>=50000) {
            JOptionPane.showMessageDialog(null, "Terima kasih telah melakukan penyetoran uang. Jumlah saldo terakhir adalah " + saldoakhir);
        }
    }//GEN-LAST:event_KirimActionPerformed

    private void BatalSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalSetorActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Transaksi().setVisible(true);
    }//GEN-LAST:event_BatalSetorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BatalSetor;
    private javax.swing.JTextField JumlahUangSetor;
    private javax.swing.JButton Kirim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
